---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade installed packages
  ansible.builtin.apt:
    upgrade: dist

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ server_timezone }}"

- name: Enable unattended upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true
