package com.jllado.weightcontrol.domain;

import java.util.Arrays;
import lombok.Getter;

@Getter
public enum PersonalRecordMetric {
    BODY_WEIGHT(PersonalRecordCatalogMetric.BODY_WEIGHT, PersonalRecordDirection.MINIMUM, "Lowest weight"),
    BODY_WEIGHT_MAXIMUM(PersonalRecordCatalogMetric.BODY_WEIGHT, PersonalRecordDirection.MAXIMUM, "Highest weight"),
    BODY_FAT_MASS(PersonalRecordCatalogMetric.BODY_FAT_MASS, PersonalRecordDirection.MINIMUM, "Lowest fat mass"),
    BODY_FAT_MASS_MAXIMUM(PersonalRecordCatalogMetric.BODY_FAT_MASS, PersonalRecordDirection.MAXIMUM, "Highest fat mass"),
    BODY_FAT_PERCENTAGE(PersonalRecordCatalogMetric.BODY_FAT_PERCENTAGE, PersonalRecordDirection.MINIMUM, "Lowest fat percentage"),
    BODY_FAT_PERCENTAGE_MAXIMUM(PersonalRecordCatalogMetric.BODY_FAT_PERCENTAGE, PersonalRecordDirection.MAXIMUM, "Highest fat percentage"),
    BODY_MUSCLE_MASS_MINIMUM(PersonalRecordCatalogMetric.BODY_MUSCLE_MASS, PersonalRecordDirection.MINIMUM, "Lowest muscle mass"),
    BODY_MUSCLE_MASS(PersonalRecordCatalogMetric.BODY_MUSCLE_MASS, PersonalRecordDirection.MAXIMUM, "Highest muscle mass"),
    BODY_MUSCLE_PERCENTAGE_MINIMUM(PersonalRecordCatalogMetric.BODY_MUSCLE_PERCENTAGE, PersonalRecordDirection.MINIMUM, "Lowest muscle percentage"),
    BODY_MUSCLE_PERCENTAGE(PersonalRecordCatalogMetric.BODY_MUSCLE_PERCENTAGE, PersonalRecordDirection.MAXIMUM, "Highest muscle percentage"),
    WORKOUT_HEAVIEST_LOAD_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_HEAVIEST_LOAD, PersonalRecordDirection.MINIMUM, "Lightest load"),
    WORKOUT_HEAVIEST_LOAD(PersonalRecordCatalogMetric.WORKOUT_HEAVIEST_LOAD, PersonalRecordDirection.MAXIMUM, "Heaviest load"),
    WORKOUT_REPETITIONS_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_REPETITIONS, PersonalRecordDirection.MINIMUM, "Fewest repetitions"),
    WORKOUT_REPETITIONS(PersonalRecordCatalogMetric.WORKOUT_REPETITIONS, PersonalRecordDirection.MAXIMUM, "Most repetitions"),
    WORKOUT_DURATION_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_DURATION, PersonalRecordDirection.MINIMUM, "Shortest duration"),
    WORKOUT_DURATION(PersonalRecordCatalogMetric.WORKOUT_DURATION, PersonalRecordDirection.MAXIMUM, "Longest duration"),
    CARDIO_DURATION_MINIMUM(PersonalRecordCatalogMetric.CARDIO_DURATION, PersonalRecordDirection.MINIMUM, "Shortest interval"),
    CARDIO_DURATION(PersonalRecordCatalogMetric.CARDIO_DURATION, PersonalRecordDirection.MAXIMUM, "Longest interval"),
    CARDIO_SPEED_MINIMUM(PersonalRecordCatalogMetric.CARDIO_SPEED, PersonalRecordDirection.MINIMUM, "Lowest speed"),
    CARDIO_SPEED(PersonalRecordCatalogMetric.CARDIO_SPEED, PersonalRecordDirection.MAXIMUM, "Highest speed"),
    CARDIO_DISTANCE_MINIMUM(PersonalRecordCatalogMetric.CARDIO_DISTANCE, PersonalRecordDirection.MINIMUM, "Shortest distance"),
    CARDIO_DISTANCE(PersonalRecordCatalogMetric.CARDIO_DISTANCE, PersonalRecordDirection.MAXIMUM, "Longest distance"),
    CARDIO_INCLINE_MINIMUM(PersonalRecordCatalogMetric.CARDIO_INCLINE, PersonalRecordDirection.MINIMUM, "Lowest incline"),
    CARDIO_INCLINE(PersonalRecordCatalogMetric.CARDIO_INCLINE, PersonalRecordDirection.MAXIMUM, "Highest incline"),
    CARDIO_RESISTANCE_MINIMUM(PersonalRecordCatalogMetric.CARDIO_RESISTANCE, PersonalRecordDirection.MINIMUM, "Lowest resistance"),
    CARDIO_RESISTANCE(PersonalRecordCatalogMetric.CARDIO_RESISTANCE, PersonalRecordDirection.MAXIMUM, "Highest resistance"),
    BLOOD_PRESSURE_SYSTOLIC_MINIMUM(PersonalRecordCatalogMetric.BLOOD_PRESSURE_SYSTOLIC, PersonalRecordDirection.MINIMUM, "Lowest systolic pressure"),
    BLOOD_PRESSURE_SYSTOLIC_MAXIMUM(PersonalRecordCatalogMetric.BLOOD_PRESSURE_SYSTOLIC, PersonalRecordDirection.MAXIMUM, "Highest systolic pressure"),
    BLOOD_PRESSURE_DIASTOLIC_MINIMUM(PersonalRecordCatalogMetric.BLOOD_PRESSURE_DIASTOLIC, PersonalRecordDirection.MINIMUM, "Lowest diastolic pressure"),
    BLOOD_PRESSURE_DIASTOLIC_MAXIMUM(PersonalRecordCatalogMetric.BLOOD_PRESSURE_DIASTOLIC, PersonalRecordDirection.MAXIMUM, "Highest diastolic pressure"),
    LIPID_TOTAL_CHOLESTEROL_MINIMUM(PersonalRecordCatalogMetric.LIPID_TOTAL_CHOLESTEROL, PersonalRecordDirection.MINIMUM, "Lowest total cholesterol"),
    LIPID_TOTAL_CHOLESTEROL_MAXIMUM(PersonalRecordCatalogMetric.LIPID_TOTAL_CHOLESTEROL, PersonalRecordDirection.MAXIMUM, "Highest total cholesterol"),
    LIPID_HDL_MINIMUM(PersonalRecordCatalogMetric.LIPID_HDL, PersonalRecordDirection.MINIMUM, "Lowest HDL"),
    LIPID_HDL_MAXIMUM(PersonalRecordCatalogMetric.LIPID_HDL, PersonalRecordDirection.MAXIMUM, "Highest HDL"),
    LIPID_LDL_MINIMUM(PersonalRecordCatalogMetric.LIPID_LDL, PersonalRecordDirection.MINIMUM, "Lowest LDL"),
    LIPID_LDL_MAXIMUM(PersonalRecordCatalogMetric.LIPID_LDL, PersonalRecordDirection.MAXIMUM, "Highest LDL"),
    LIPID_TRIGLYCERIDES_MINIMUM(PersonalRecordCatalogMetric.LIPID_TRIGLYCERIDES, PersonalRecordDirection.MINIMUM, "Lowest triglycerides"),
    LIPID_TRIGLYCERIDES_MAXIMUM(PersonalRecordCatalogMetric.LIPID_TRIGLYCERIDES, PersonalRecordDirection.MAXIMUM, "Highest triglycerides"),
    MOOD_MINIMUM(PersonalRecordCatalogMetric.MOOD, PersonalRecordDirection.MINIMUM, "Lowest mood"),
    MOOD_MAXIMUM(PersonalRecordCatalogMetric.MOOD, PersonalRecordDirection.MAXIMUM, "Highest mood"),
    SLEEP_TOTAL_DURATION_MINIMUM(PersonalRecordCatalogMetric.SLEEP_TOTAL_DURATION, PersonalRecordDirection.MINIMUM, "Shortest total sleep"),
    SLEEP_TOTAL_DURATION_MAXIMUM(PersonalRecordCatalogMetric.SLEEP_TOTAL_DURATION, PersonalRecordDirection.MAXIMUM, "Longest total sleep"),
    SLEEP_DEEP_DURATION_MINIMUM(PersonalRecordCatalogMetric.SLEEP_DEEP_DURATION, PersonalRecordDirection.MINIMUM, "Shortest deep sleep"),
    SLEEP_DEEP_DURATION_MAXIMUM(PersonalRecordCatalogMetric.SLEEP_DEEP_DURATION, PersonalRecordDirection.MAXIMUM, "Longest deep sleep"),
    SLEEP_REM_DURATION_MINIMUM(PersonalRecordCatalogMetric.SLEEP_REM_DURATION, PersonalRecordDirection.MINIMUM, "Shortest REM sleep"),
    SLEEP_REM_DURATION_MAXIMUM(PersonalRecordCatalogMetric.SLEEP_REM_DURATION, PersonalRecordDirection.MAXIMUM, "Longest REM sleep"),
    SLEEP_LIGHT_DURATION_MINIMUM(PersonalRecordCatalogMetric.SLEEP_LIGHT_DURATION, PersonalRecordDirection.MINIMUM, "Shortest light sleep"),
    SLEEP_LIGHT_DURATION_MAXIMUM(PersonalRecordCatalogMetric.SLEEP_LIGHT_DURATION, PersonalRecordDirection.MAXIMUM, "Longest light sleep"),
    SLEEP_AWAKE_TIME_MINIMUM(PersonalRecordCatalogMetric.SLEEP_AWAKE_TIME, PersonalRecordDirection.MINIMUM, "Shortest awake time"),
    SLEEP_AWAKE_TIME_MAXIMUM(PersonalRecordCatalogMetric.SLEEP_AWAKE_TIME, PersonalRecordDirection.MAXIMUM, "Longest awake time"),
    SLEEP_AVERAGE_HEART_RATE_MINIMUM(PersonalRecordCatalogMetric.SLEEP_AVERAGE_HEART_RATE, PersonalRecordDirection.MINIMUM, "Lowest sleep heart rate"),
    SLEEP_AVERAGE_HEART_RATE_MAXIMUM(PersonalRecordCatalogMetric.SLEEP_AVERAGE_HEART_RATE, PersonalRecordDirection.MAXIMUM, "Highest sleep heart rate"),
    SLEEP_AVERAGE_HRV_MINIMUM(PersonalRecordCatalogMetric.SLEEP_AVERAGE_HRV, PersonalRecordDirection.MINIMUM, "Lowest HRV"),
    SLEEP_AVERAGE_HRV_MAXIMUM(PersonalRecordCatalogMetric.SLEEP_AVERAGE_HRV, PersonalRecordDirection.MAXIMUM, "Highest HRV"),
    MEAL_CALORIES_MINIMUM(PersonalRecordCatalogMetric.MEAL_CALORIES, PersonalRecordDirection.MINIMUM, "Lowest meal calories"),
    MEAL_CALORIES_MAXIMUM(PersonalRecordCatalogMetric.MEAL_CALORIES, PersonalRecordDirection.MAXIMUM, "Highest meal calories"),
    MEAL_PROTEIN_MINIMUM(PersonalRecordCatalogMetric.MEAL_PROTEIN, PersonalRecordDirection.MINIMUM, "Lowest meal protein"),
    MEAL_PROTEIN_MAXIMUM(PersonalRecordCatalogMetric.MEAL_PROTEIN, PersonalRecordDirection.MAXIMUM, "Highest meal protein"),
    MEAL_CARBOHYDRATES_MINIMUM(PersonalRecordCatalogMetric.MEAL_CARBOHYDRATES, PersonalRecordDirection.MINIMUM, "Lowest meal carbohydrates"),
    MEAL_CARBOHYDRATES_MAXIMUM(PersonalRecordCatalogMetric.MEAL_CARBOHYDRATES, PersonalRecordDirection.MAXIMUM, "Highest meal carbohydrates"),
    MEAL_FAT_MINIMUM(PersonalRecordCatalogMetric.MEAL_FAT, PersonalRecordDirection.MINIMUM, "Lowest meal fat"),
    MEAL_FAT_MAXIMUM(PersonalRecordCatalogMetric.MEAL_FAT, PersonalRecordDirection.MAXIMUM, "Highest meal fat"),
    DAILY_CALORIES_MINIMUM(PersonalRecordCatalogMetric.DAILY_CALORIES, PersonalRecordDirection.MINIMUM, "Lowest daily calories"),
    DAILY_CALORIES_MAXIMUM(PersonalRecordCatalogMetric.DAILY_CALORIES, PersonalRecordDirection.MAXIMUM, "Highest daily calories"),
    DAILY_PROTEIN_MINIMUM(PersonalRecordCatalogMetric.DAILY_PROTEIN, PersonalRecordDirection.MINIMUM, "Lowest daily protein"),
    DAILY_PROTEIN_MAXIMUM(PersonalRecordCatalogMetric.DAILY_PROTEIN, PersonalRecordDirection.MAXIMUM, "Highest daily protein"),
    DAILY_CARBOHYDRATES_MINIMUM(PersonalRecordCatalogMetric.DAILY_CARBOHYDRATES, PersonalRecordDirection.MINIMUM, "Lowest daily carbohydrates"),
    DAILY_CARBOHYDRATES_MAXIMUM(PersonalRecordCatalogMetric.DAILY_CARBOHYDRATES, PersonalRecordDirection.MAXIMUM, "Highest daily carbohydrates"),
    DAILY_FAT_MINIMUM(PersonalRecordCatalogMetric.DAILY_FAT, PersonalRecordDirection.MINIMUM, "Lowest daily fat"),
    DAILY_FAT_MAXIMUM(PersonalRecordCatalogMetric.DAILY_FAT, PersonalRecordDirection.MAXIMUM, "Highest daily fat"),
    HABIT_COMPLETION_TOTAL_MINIMUM(PersonalRecordCatalogMetric.HABIT_COMPLETION_TOTAL, PersonalRecordDirection.MINIMUM, "Fewest habit completions"),
    HABIT_COMPLETION_TOTAL_MAXIMUM(PersonalRecordCatalogMetric.HABIT_COMPLETION_TOTAL, PersonalRecordDirection.MAXIMUM, "Most habit completions"),
    HABIT_CURRENT_STREAK_MINIMUM(PersonalRecordCatalogMetric.HABIT_CURRENT_STREAK, PersonalRecordDirection.MINIMUM, "Shortest habit current streak"),
    HABIT_CURRENT_STREAK_MAXIMUM(PersonalRecordCatalogMetric.HABIT_CURRENT_STREAK, PersonalRecordDirection.MAXIMUM, "Longest habit current streak"),
    HABIT_BEST_STREAK_MINIMUM(PersonalRecordCatalogMetric.HABIT_BEST_STREAK, PersonalRecordDirection.MINIMUM, "Lowest habit best streak"),
    HABIT_BEST_STREAK_MAXIMUM(PersonalRecordCatalogMetric.HABIT_BEST_STREAK, PersonalRecordDirection.MAXIMUM, "Highest habit best streak"),
    ROUTINE_BEST_STREAK_MINIMUM(PersonalRecordCatalogMetric.ROUTINE_BEST_STREAK, PersonalRecordDirection.MINIMUM, "Lowest routine best streak"),
    ROUTINE_BEST_STREAK_MAXIMUM(PersonalRecordCatalogMetric.ROUTINE_BEST_STREAK, PersonalRecordDirection.MAXIMUM, "Highest routine best streak"),
    BODY_BMI_MINIMUM(PersonalRecordCatalogMetric.BODY_BMI, PersonalRecordDirection.MINIMUM, "Lowest BMI"),
    BODY_BMI_MAXIMUM(PersonalRecordCatalogMetric.BODY_BMI, PersonalRecordDirection.MAXIMUM, "Highest BMI"),
    WORKOUT_SESSION_COUNT_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_SESSION_COUNT, PersonalRecordDirection.MINIMUM, "Fewest workouts"),
    WORKOUT_SESSION_COUNT_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_SESSION_COUNT, PersonalRecordDirection.MAXIMUM, "Most workouts"),
    WORKOUT_SET_COUNT_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_SET_COUNT, PersonalRecordDirection.MINIMUM, "Fewest sets"),
    WORKOUT_SET_COUNT_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_SET_COUNT, PersonalRecordDirection.MAXIMUM, "Most sets"),
    WORKOUT_INTERVAL_COUNT_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_INTERVAL_COUNT, PersonalRecordDirection.MINIMUM, "Fewest intervals"),
    WORKOUT_INTERVAL_COUNT_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_INTERVAL_COUNT, PersonalRecordDirection.MAXIMUM, "Most intervals"),
    WORKOUT_STRENGTH_VOLUME_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_STRENGTH_VOLUME, PersonalRecordDirection.MINIMUM, "Lowest strength volume"),
    WORKOUT_STRENGTH_VOLUME_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_STRENGTH_VOLUME, PersonalRecordDirection.MAXIMUM, "Highest strength volume"),
    WORKOUT_CALORIES_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_CALORIES, PersonalRecordDirection.MINIMUM, "Lowest workout calories"),
    WORKOUT_CALORIES_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_CALORIES, PersonalRecordDirection.MAXIMUM, "Highest workout calories"),
    WORKOUT_AVERAGE_HEART_RATE_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_AVERAGE_HEART_RATE, PersonalRecordDirection.MINIMUM, "Lowest workout heart rate"),
    WORKOUT_AVERAGE_HEART_RATE_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_AVERAGE_HEART_RATE, PersonalRecordDirection.MAXIMUM, "Highest workout heart rate"),
    DASHBOARD_TOTAL_COUNT_MINIMUM(PersonalRecordCatalogMetric.DASHBOARD_TOTAL_COUNT, PersonalRecordDirection.MINIMUM, "Fewest dashboard opportunities"),
    DASHBOARD_TOTAL_COUNT_MAXIMUM(PersonalRecordCatalogMetric.DASHBOARD_TOTAL_COUNT, PersonalRecordDirection.MAXIMUM, "Most dashboard opportunities"),
    DASHBOARD_COMPLETED_COUNT_MINIMUM(PersonalRecordCatalogMetric.DASHBOARD_COMPLETED_COUNT, PersonalRecordDirection.MINIMUM, "Fewest dashboard completions"),
    DASHBOARD_COMPLETED_COUNT_MAXIMUM(PersonalRecordCatalogMetric.DASHBOARD_COMPLETED_COUNT, PersonalRecordDirection.MAXIMUM, "Most dashboard completions"),
    DASHBOARD_COMPLETION_PERCENTAGE_MINIMUM(PersonalRecordCatalogMetric.DASHBOARD_COMPLETION_PERCENTAGE, PersonalRecordDirection.MINIMUM, "Lowest dashboard completion"),
    DASHBOARD_COMPLETION_PERCENTAGE_MAXIMUM(PersonalRecordCatalogMetric.DASHBOARD_COMPLETION_PERCENTAGE, PersonalRecordDirection.MAXIMUM, "Highest dashboard completion"),
    DASHBOARD_SCORE_MINIMUM(PersonalRecordCatalogMetric.DASHBOARD_SCORE, PersonalRecordDirection.MINIMUM, "Lowest dashboard score"),
    DASHBOARD_SCORE_MAXIMUM(PersonalRecordCatalogMetric.DASHBOARD_SCORE, PersonalRecordDirection.MAXIMUM, "Highest dashboard score"),
    DASHBOARD_STATUS_MINIMUM(PersonalRecordCatalogMetric.DASHBOARD_STATUS, PersonalRecordDirection.MINIMUM, "Lowest dashboard status"),
    DASHBOARD_STATUS_MAXIMUM(PersonalRecordCatalogMetric.DASHBOARD_STATUS, PersonalRecordDirection.MAXIMUM, "Highest dashboard status"),
    CHANGE_KG_MINIMUM(PersonalRecordCatalogMetric.CHANGE_KG, PersonalRecordDirection.MINIMUM, "Lowest mass change"),
    CHANGE_KG_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_KG, PersonalRecordDirection.MAXIMUM, "Highest mass change"),
    CHANGE_PERCENT_MINIMUM(PersonalRecordCatalogMetric.CHANGE_PERCENT, PersonalRecordDirection.MINIMUM, "Lowest percentage change"),
    CHANGE_PERCENT_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_PERCENT, PersonalRecordDirection.MAXIMUM, "Highest percentage change"),
    CHANGE_MM_HG_MINIMUM(PersonalRecordCatalogMetric.CHANGE_MM_HG, PersonalRecordDirection.MINIMUM, "Lowest pressure change"),
    CHANGE_MM_HG_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_MM_HG, PersonalRecordDirection.MAXIMUM, "Highest pressure change"),
    CHANGE_MG_PER_DL_MINIMUM(PersonalRecordCatalogMetric.CHANGE_MG_PER_DL, PersonalRecordDirection.MINIMUM, "Lowest lipid change"),
    CHANGE_MG_PER_DL_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_MG_PER_DL, PersonalRecordDirection.MAXIMUM, "Highest lipid change"),
    CHANGE_SECONDS_MINIMUM(PersonalRecordCatalogMetric.CHANGE_SECONDS, PersonalRecordDirection.MINIMUM, "Lowest duration change"),
    CHANGE_SECONDS_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_SECONDS, PersonalRecordDirection.MAXIMUM, "Highest duration change"),
    CHANGE_BPM_MINIMUM(PersonalRecordCatalogMetric.CHANGE_BPM, PersonalRecordDirection.MINIMUM, "Lowest heart-rate change"),
    CHANGE_BPM_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_BPM, PersonalRecordDirection.MAXIMUM, "Highest heart-rate change"),
    CHANGE_MILLISECONDS_MINIMUM(PersonalRecordCatalogMetric.CHANGE_MILLISECONDS, PersonalRecordDirection.MINIMUM, "Lowest HRV change"),
    CHANGE_MILLISECONDS_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_MILLISECONDS, PersonalRecordDirection.MAXIMUM, "Highest HRV change"),
    RECOVERY_CHANGE_SCORE_MINIMUM(PersonalRecordCatalogMetric.RECOVERY_CHANGE_SCORE, PersonalRecordDirection.MINIMUM, "Lowest recovery score change"),
    RECOVERY_CHANGE_SCORE_MAXIMUM(PersonalRecordCatalogMetric.RECOVERY_CHANGE_SCORE, PersonalRecordDirection.MAXIMUM, "Highest recovery score change"),
    CHANGE_KCAL_MINIMUM(PersonalRecordCatalogMetric.CHANGE_KCAL, PersonalRecordDirection.MINIMUM, "Lowest calorie change"),
    CHANGE_KCAL_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_KCAL, PersonalRecordDirection.MAXIMUM, "Highest calorie change"),
    CHANGE_SCORE_MINIMUM(PersonalRecordCatalogMetric.CHANGE_SCORE, PersonalRecordDirection.MINIMUM, "Lowest score change"),
    CHANGE_SCORE_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_SCORE, PersonalRecordDirection.MAXIMUM, "Highest score change"),
    BEHAVIOR_CHANGE_PERCENT_MINIMUM(PersonalRecordCatalogMetric.BEHAVIOR_CHANGE_PERCENT, PersonalRecordDirection.MINIMUM, "Lowest behavior percentage change"),
    BEHAVIOR_CHANGE_PERCENT_MAXIMUM(PersonalRecordCatalogMetric.BEHAVIOR_CHANGE_PERCENT, PersonalRecordDirection.MAXIMUM, "Highest behavior percentage change"),
    WORKOUT_CHANGE_COUNT_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_CHANGE_COUNT, PersonalRecordDirection.MINIMUM, "Lowest workout count change"),
    WORKOUT_CHANGE_COUNT_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_CHANGE_COUNT, PersonalRecordDirection.MAXIMUM, "Highest workout count change"),
    WORKOUT_CHANGE_SECONDS_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_CHANGE_SECONDS, PersonalRecordDirection.MINIMUM, "Lowest workout duration change"),
    WORKOUT_CHANGE_SECONDS_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_CHANGE_SECONDS, PersonalRecordDirection.MAXIMUM, "Highest workout duration change"),
    WORKOUT_CHANGE_KCAL_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_CHANGE_KCAL, PersonalRecordDirection.MINIMUM, "Lowest workout calorie change"),
    WORKOUT_CHANGE_KCAL_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_CHANGE_KCAL, PersonalRecordDirection.MAXIMUM, "Highest workout calorie change"),
    WORKOUT_CHANGE_BPM_MINIMUM(PersonalRecordCatalogMetric.WORKOUT_CHANGE_BPM, PersonalRecordDirection.MINIMUM, "Lowest workout heart-rate change"),
    WORKOUT_CHANGE_BPM_MAXIMUM(PersonalRecordCatalogMetric.WORKOUT_CHANGE_BPM, PersonalRecordDirection.MAXIMUM, "Highest workout heart-rate change"),
    CHANGE_KM_MINIMUM(PersonalRecordCatalogMetric.CHANGE_KM, PersonalRecordDirection.MINIMUM, "Lowest distance change"),
    CHANGE_KM_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_KM, PersonalRecordDirection.MAXIMUM, "Highest distance change"),
    CHANGE_KG_REPETITIONS_MINIMUM(PersonalRecordCatalogMetric.CHANGE_KG_REPETITIONS, PersonalRecordDirection.MINIMUM, "Lowest volume change"),
    CHANGE_KG_REPETITIONS_MAXIMUM(PersonalRecordCatalogMetric.CHANGE_KG_REPETITIONS, PersonalRecordDirection.MAXIMUM, "Highest volume change"),
    TARGET_DIFFERENCE_KCAL_MINIMUM(PersonalRecordCatalogMetric.TARGET_DIFFERENCE_KCAL, PersonalRecordDirection.MINIMUM, "Lowest calorie target difference"),
    TARGET_DIFFERENCE_KCAL_MAXIMUM(PersonalRecordCatalogMetric.TARGET_DIFFERENCE_KCAL, PersonalRecordDirection.MAXIMUM, "Highest calorie target difference");

    private final PersonalRecordCatalogMetric catalogMetric;
    private final PersonalRecordDirection direction;
    private final String label;

    PersonalRecordMetric(PersonalRecordCatalogMetric catalogMetric, PersonalRecordDirection direction, String label) {
        this.catalogMetric = catalogMetric;
        this.direction = direction;
        this.label = label;
    }

    public PersonalRecordDomain getDomain() { return catalogMetric.getDomain(); }
    public PersonalRecordUnit getUnit() { return catalogMetric.getUnit(); }
    public String getSubjectLabel() { return catalogMetric.getSubjectLabel(); }

    public static PersonalRecordMetric forDirection(PersonalRecordCatalogMetric catalogMetric, PersonalRecordDirection direction) {
        return Arrays.stream(values()).filter(metric -> metric.catalogMetric == catalogMetric && metric.direction == direction).findFirst().orElseThrow();
    }
}
